### ISSUE TITLE
 Fuzz Testing Multiple ABI and BIN Files

### ISSUE THREAD

**Issue by qianqianpang** [SoftSec-KAIST/Smartian#10]
Dear Author,

I hope this message finds you well. I have read your article and attempted to replicate the tool. Following the usage guide provided in the README, I was able to successfully fuzz a single `.bin` and `.abi` contract and identify vulnerabilities.
![image](https://github.com/user-attachments/assets/3965dfb5-641f-4eb5-9282-87fa5cbf0210)
 However, when a contract generates multiple `.abi` and `.bin` files after compilation, how should I use the command to conduct fuzz testing in this case?

**Comment by jchoi2022** [comment]
If a source code file contains (defines) multiple contracts, then the compiler will generate multiple `.bin` and `.abi` files. This often occurs when one contract inherits another one.

In such case, you must manually decide which is the contract that you want to test, and provide appropriate one to the testing tool. For this reason, other testing tools (especially source-based testing tools) also ask the user to specify the target contract to focus on.

**Comment by qianqianpang** [comment]
thanks!
