### ISSUE TITLE
Unable to build Smartian due to SSL error in Nethermind

### ISSUE THREAD

**Issue by faustocarva** [SoftSec-KAIST/Smartian#8]
Hi, I'm trying to compile Samaritan, and I'm getting the error below:
![2024-05-04_16-54](https://github.com/SoftSec-KAIST/Smartian/assets/279197/593d0697-021c-4fc9-ae8d-9420c0103a4e)

It looks like a SSL certificate issue with the site https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
This site is used in the Nuget.config file in Nethermind: 
` <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />`

**Comment by jchoi2022** [comment]
There seems to have been lots of change to .NET environment since the last update. I fixed this issue in the latest commit (badd4ff) of `main` branch. Please let me know if you still experience the same issue.

**Comment by faustocarva** [comment]
It works now.
